/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Tongquan;

import com.raven.chart.ModelChart;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import com.QLKH.model.DatabaseHelper;

/**
 *
 * @author doqua
 */
public class tongquan extends javax.swing.JFrame {

    ArrayList<kho> list = new ArrayList<>();

    /**
     * Creates new form tongquan
     */
    public tongquan() {
        list.clear();
        initComponents();
        setLocationRelativeTo(null);
        init();
        LoadData();
    }

    private void LoadData() {
        try {
            list.clear();
            Connection con = DatabaseHelper.oppenConnection();
            PreparedStatement ps = con.prepareStatement("select dtkho, dtchua,dtdgdi,dtsd from Khotong");

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                kho k = new kho();
                //1. gan du lieu cho sv
                k.setDtkho(rs.getInt("dtkho"));
                k.setDtchua(rs.getInt("dtchua"));
                k.setDtdgdi(rs.getInt("dtdgdi"));
                k.setDtsd(rs.getInt("dtsd"));
                list.add(k);
                Chart1.setValue(k.getDtsd());
                Chart1.start();
                System.out.println(k.getDtsd());
            }

            ps.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
         try {
            list.clear();
            Connection con = DatabaseHelper.oppenConnection();
            PreparedStatement ps = con.prepareStatement("select dtkho, dtchua,dtdgdi,dtsd from Kho1");

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                kho k = new kho();
                //1. gan du lieu cho sv
                k.setDtkho(rs.getInt("dtkho"));
                k.setDtchua(rs.getInt("dtchua"));
                k.setDtdgdi(rs.getInt("dtdgdi"));
                k.setDtsd(rs.getInt("dtsd"));
                list.add(k);
                Chart2.setValue(k.getDtsd());
                Chart2.start();
                System.out.println(k.getDtsd());
            }

            ps.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
          try {
            list.clear();
            Connection con = DatabaseHelper.oppenConnection();
            PreparedStatement ps = con.prepareStatement("select dtkho, dtchua,dtdgdi,dtsd from Kho2");

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                kho k = new kho();
                //1. gan du lieu cho sv
                k.setDtkho(rs.getInt("dtkho"));
                k.setDtchua(rs.getInt("dtchua"));
                k.setDtdgdi(rs.getInt("dtdgdi"));
                k.setDtsd(rs.getInt("dtsd"));
                list.add(k);
                Chart3.setValue(k.getDtsd());
                Chart3.start();
                System.out.println(k.getDtsd());
            }

            ps.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
           try {
            list.clear();
            Connection con = DatabaseHelper.oppenConnection();
            PreparedStatement ps = con.prepareStatement("select dtkho, dtchua,dtdgdi,dtsd from Kho3");

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                kho k = new kho();
                //1. gan du lieu cho sv
                k.setDtkho(rs.getInt("dtkho"));
                k.setDtchua(rs.getInt("dtchua"));
                k.setDtdgdi(rs.getInt("dtdgdi"));
                k.setDtsd(rs.getInt("dtsd"));
                list.add(k);
                Chart4.setValue(k.getDtsd());
                Chart4.start();
                System.out.println(k.getDtsd());
            }

            ps.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void init() {
Chart.addLegend("Hàng nhập", Color.yellow, Color.red);
Chart.addLegend("Hàng xuất", Color.blue, Color.green);
Chart.addData(new ModelChart("01/10", new double[]{500,200}));
Chart.addData(new ModelChart("05/10", new double[]{500,200}));
Chart.addData(new ModelChart("10/10", new double[]{500,200}));
Chart.start();

    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        progress8 = new com.raven.swing.progress.Progress();
        jLabel6 = new javax.swing.JLabel();
        pnlBackground = new javax.swing.JPanel();
        pnlFooter = new javax.swing.JPanel();
        pnlBanhang = new com.raven.swing.RoundPanel();
        Chart = new com.raven.chart.Chart();
        lblBieudobanhang = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        roundPanel2 = new com.raven.swing.RoundPanel();
        pnlSucchuakho = new com.raven.swing.RoundPanel();
        lblBieudosucchuakho = new javax.swing.JLabel();
        pnlChart1 = new javax.swing.JPanel();
        Chart1 = new com.raven.swing.progress.Progress();
        lblChart1 = new javax.swing.JLabel();
        pnlChart2 = new javax.swing.JPanel();
        Chart2 = new com.raven.swing.progress.Progress();
        lblChart2 = new javax.swing.JLabel();
        pnlChart3 = new javax.swing.JPanel();
        Chart3 = new com.raven.swing.progress.Progress();
        lblChart3 = new javax.swing.JLabel();
        pnlChart4 = new javax.swing.JPanel();
        Chart4 = new com.raven.swing.progress.Progress();
        lblChart4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mTongquan = new javax.swing.JMenu();
        mDanhmucsp = new javax.swing.JMenu();
        mhanghoa = new javax.swing.JMenu();
        mNhanvien = new javax.swing.JMenu();
        mChamcong = new javax.swing.JMenu();
        mLuong = new javax.swing.JMenu();
        mNhacungcap = new javax.swing.JMenu();
        mLichsunhap = new javax.swing.JMenu();
        mNonhacungcap = new javax.swing.JMenu();
        mThongke = new javax.swing.JMenu();
        mDoanhthutong = new javax.swing.JMenu();
        mDoanhthutungcuahang = new javax.swing.JMenu();
        mChitieu = new javax.swing.JMenu();

        jPanel5.setOpaque(false);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Kho tổng");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(progress8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(9, 9, 9)
                .addComponent(progress8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBackground.setBackground(new java.awt.Color(153, 153, 153));
        pnlBackground.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        pnlBanhang.setBackground(new java.awt.Color(255, 255, 255));

        Chart.setBackground(new java.awt.Color(0, 0, 0));
        Chart.setForeground(new java.awt.Color(0, 0, 0));
        Chart.setToolTipText("");

        lblBieudobanhang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBieudobanhang.setForeground(new java.awt.Color(0, 0, 0));
        lblBieudobanhang.setText("Biểu đồ bán hàng");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hôm nay", "Tuần trước", "Tháng trước" }));

        javax.swing.GroupLayout pnlBanhangLayout = new javax.swing.GroupLayout(pnlBanhang);
        pnlBanhang.setLayout(pnlBanhangLayout);
        pnlBanhangLayout.setHorizontalGroup(
            pnlBanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanhangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Chart, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addGroup(pnlBanhangLayout.createSequentialGroup()
                        .addComponent(lblBieudobanhang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlBanhangLayout.setVerticalGroup(
            pnlBanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBanhangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBieudobanhang)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(Chart, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        roundPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        pnlSucchuakho.setBackground(new java.awt.Color(255, 255, 255));
        pnlSucchuakho.setForeground(new java.awt.Color(0, 0, 0));

        lblBieudosucchuakho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBieudosucchuakho.setForeground(new java.awt.Color(0, 0, 0));
        lblBieudosucchuakho.setText("Biểu đồ sức chứa kho");

        pnlChart1.setOpaque(false);

        Chart1.setBackground(new java.awt.Color(51, 51, 255));
        Chart1.setForeground(new java.awt.Color(255, 0, 51));
        Chart1.setValue(60);

        lblChart1.setForeground(new java.awt.Color(0, 0, 0));
        lblChart1.setText("Kho tổng");

        javax.swing.GroupLayout pnlChart1Layout = new javax.swing.GroupLayout(pnlChart1);
        pnlChart1.setLayout(pnlChart1Layout);
        pnlChart1Layout.setHorizontalGroup(
            pnlChart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChart1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Chart1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlChart1Layout.setVerticalGroup(
            pnlChart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChart1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChart1)
                .addGap(9, 9, 9)
                .addComponent(Chart1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlChart2.setOpaque(false);

        Chart2.setBackground(new java.awt.Color(51, 51, 255));
        Chart2.setForeground(new java.awt.Color(255, 0, 51));

        lblChart2.setForeground(new java.awt.Color(0, 0, 0));
        lblChart2.setText("Kho 1");

        javax.swing.GroupLayout pnlChart2Layout = new javax.swing.GroupLayout(pnlChart2);
        pnlChart2.setLayout(pnlChart2Layout);
        pnlChart2Layout.setHorizontalGroup(
            pnlChart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChart2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Chart2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChart2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlChart2Layout.setVerticalGroup(
            pnlChart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChart2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChart2)
                .addGap(9, 9, 9)
                .addComponent(Chart2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlChart3.setOpaque(false);

        Chart3.setBackground(new java.awt.Color(51, 51, 255));
        Chart3.setForeground(new java.awt.Color(255, 0, 51));

        lblChart3.setForeground(new java.awt.Color(0, 0, 0));
        lblChart3.setText("Kho 2");

        javax.swing.GroupLayout pnlChart3Layout = new javax.swing.GroupLayout(pnlChart3);
        pnlChart3.setLayout(pnlChart3Layout);
        pnlChart3Layout.setHorizontalGroup(
            pnlChart3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChart3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChart3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Chart3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChart3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlChart3Layout.setVerticalGroup(
            pnlChart3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChart3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChart3)
                .addGap(9, 9, 9)
                .addComponent(Chart3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlChart4.setOpaque(false);

        Chart4.setBackground(new java.awt.Color(51, 51, 255));
        Chart4.setForeground(new java.awt.Color(255, 0, 51));

        lblChart4.setForeground(new java.awt.Color(0, 0, 0));
        lblChart4.setText("Kho 3");

        javax.swing.GroupLayout pnlChart4Layout = new javax.swing.GroupLayout(pnlChart4);
        pnlChart4.setLayout(pnlChart4Layout);
        pnlChart4Layout.setHorizontalGroup(
            pnlChart4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChart4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChart4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Chart4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChart4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlChart4Layout.setVerticalGroup(
            pnlChart4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChart4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChart4)
                .addGap(9, 9, 9)
                .addComponent(Chart4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlSucchuakhoLayout = new javax.swing.GroupLayout(pnlSucchuakho);
        pnlSucchuakho.setLayout(pnlSucchuakhoLayout);
        pnlSucchuakhoLayout.setHorizontalGroup(
            pnlSucchuakhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSucchuakhoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSucchuakhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBieudosucchuakho)
                    .addGroup(pnlSucchuakhoLayout.createSequentialGroup()
                        .addGroup(pnlSucchuakhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlChart3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlChart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlSucchuakhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlChart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlChart4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        pnlSucchuakhoLayout.setVerticalGroup(
            pnlSucchuakhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSucchuakhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBieudosucchuakho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSucchuakhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlChart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlChart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSucchuakhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlChart3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlChart4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(roundPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(pnlBanhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlSucchuakho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlBanhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSucchuakho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        mTongquan.setText("Tổng quan");
        jMenuBar1.add(mTongquan);

        mDanhmucsp.setText("Danh mục sản phẩm");
        jMenuBar1.add(mDanhmucsp);

        mhanghoa.setText("Hàng hóa");
        jMenuBar1.add(mhanghoa);

        mNhanvien.setText("Nhân viên");

        mChamcong.setText("Chấm công");
        mNhanvien.add(mChamcong);

        mLuong.setText("Lương");
        mNhanvien.add(mLuong);

        jMenuBar1.add(mNhanvien);

        mNhacungcap.setText("Nhà cung cấp");

        mLichsunhap.setText("Lịch sử nhập");
        mNhacungcap.add(mLichsunhap);

        mNonhacungcap.setText("Nợ NCC");
        mNhacungcap.add(mNonhacungcap);

        jMenuBar1.add(mNhacungcap);

        mThongke.setText("Thống kê");

        mDoanhthutong.setText("Doanh thu tổng");
        mThongke.add(mDoanhthutong);

        mDoanhthutungcuahang.setText("Doanh thu từng cửa hàng");
        mThongke.add(mDoanhthutungcuahang);

        mChitieu.setText("Chi tiêu");
        mThongke.add(mChitieu);

        jMenuBar1.add(mThongke);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tongquan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tongquan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tongquan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tongquan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tongquan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.chart.Chart Chart;
    private com.raven.swing.progress.Progress Chart1;
    private com.raven.swing.progress.Progress Chart2;
    private com.raven.swing.progress.Progress Chart3;
    private com.raven.swing.progress.Progress Chart4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblBieudobanhang;
    private javax.swing.JLabel lblBieudosucchuakho;
    private javax.swing.JLabel lblChart1;
    private javax.swing.JLabel lblChart2;
    private javax.swing.JLabel lblChart3;
    private javax.swing.JLabel lblChart4;
    private javax.swing.JMenu mChamcong;
    private javax.swing.JMenu mChitieu;
    private javax.swing.JMenu mDanhmucsp;
    private javax.swing.JMenu mDoanhthutong;
    private javax.swing.JMenu mDoanhthutungcuahang;
    private javax.swing.JMenu mLichsunhap;
    private javax.swing.JMenu mLuong;
    private javax.swing.JMenu mNhacungcap;
    private javax.swing.JMenu mNhanvien;
    private javax.swing.JMenu mNonhacungcap;
    private javax.swing.JMenu mThongke;
    private javax.swing.JMenu mTongquan;
    private javax.swing.JMenu mhanghoa;
    private javax.swing.JPanel pnlBackground;
    private com.raven.swing.RoundPanel pnlBanhang;
    private javax.swing.JPanel pnlChart1;
    private javax.swing.JPanel pnlChart2;
    private javax.swing.JPanel pnlChart3;
    private javax.swing.JPanel pnlChart4;
    private javax.swing.JPanel pnlFooter;
    private com.raven.swing.RoundPanel pnlSucchuakho;
    private com.raven.swing.progress.Progress progress8;
    private com.raven.swing.RoundPanel roundPanel2;
    // End of variables declaration//GEN-END:variables
}
